### PR TITLE
Relax license of my own contributions

### PR DESCRIPTION
**Pull request by samv**
As requested.  Principally allows the Artistic v2 license, which permits
relicensing under the terms of other free licenses.

@rurban, a GNU software author is asking for this: could you roll this notice into the next release?

Cheers, Sam

### CODE REVIEW

**Comment by samv** [comment]
@jll63 do you also care to relax the core license of the module along similar lines?

**Comment by samv** [comment]
Also @catalyst - some of my contributions to this project were on the clock

**Comment by puck** [comment]
@catalyst is happy for the the contributions made by @samv on our time to have the change that he has proposed, and feel that the wording should also say contributions made on our time can be under either v1 or future versions as seen fit (the same wording as @samv has used for his contributions).

Approved by Don Christie, a director of Catalyst IT.

**Comment by cwebber** [comment]
This is great!  Thank you!

**Pull request merged**
