### PR TITLE
use meta-spec 2, Moose -> dev.requires not runtime.recommends

### PR DESCRIPTION
**Pull request by mohawk2**
As discussed on https://rt.cpan.org/Ticket/Display.html?id=134034

Cc: @briandfoy

### CODE REVIEW

**Comment by mohawk2** [comment]
Also discussed on https://github.com/graphviz-perl/Graph/issues/17 and https://github.com/klp2/Make/issues/12

**Comment by haarg** [comment]
Looks like you copied the wrong bug tracker information.

**Comment by mohawk2** [comment]
@haarg Great catch, thanks!

**Comment by mohawk2** [comment]
That would have been *very* confusing.

**Pull request merged**
